---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitlab-exporter.fullname" . }}
  labels:
    {{- include "gitlab-exporter.labels" . | nindent 4 }}
data:
  GITLAB_API_URL: ""
  GITLAB_PERSONAL_ACCESS_TOKEN: ""
